import Script from 'next/script'
import { Geist, Geist_Mono } from 'next/font/google'
import '../css/styles.css'
import '../css/plugins/bootstrap.min.css'
import '../css/plugins/magnific-popup.css'
import '../css/plugins/themify-icons.css'
import '../css/plugins/animate.min.css'
import '../css/plugins/owl.carousel.min.css'
import '../css/plugins/owl.theme.default.min.css'
import '../css/plugins/YouTubePopUp.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: [ 'latin' ]
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: [ 'latin' ]
})

export const metadata = {
  title: 'Medi Architect',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      {children}
      <Script src="/js/jquery-3.6.3.min.js" strategy="beforeInteractive"/>
      <Script src="/js/jquery-migrate-3.0.0.min.js" strategy="beforeInteractive"/>
      <Script src="/js/modernizr-2.6.2.min.js" strategy="beforeInteractive"/>
      <Script src="/js/imagesloaded.pkgd.min.js" strategy="beforeInteractive"/>
      <Script src="/js/jquery.isotope.v3.0.2.js" strategy="beforeInteractive"/>
      <Script src="/js/popper.min.js" strategy="beforeInteractive"/>
      <Script src="/js/bootstrap.min.js" strategy="beforeInteractive"/>
      <Script src="/js/scrollIt.min.js" strategy="beforeInteractive"/>
      <Script src="/js/jquery.waypoints.min.js" strategy="beforeInteractive"/>
      <Script src="/js/owl.carousel.min.js" strategy="lazyOnload"/>
      <Script src="/js/jquery.stellar.min.js" strategy="lazyOnload"/>
      <Script src="/js/jquery.magnific-popup.js" strategy="lazyOnload"/>
      <Script src="/js/YouTubePopUp.js" strategy="lazyOnload"/>
      <Script src="/js/before-after.js" strategy="lazyOnload"/>
      <Script src="/js/custom.js" strategy="lazyOnload"/>
      </body>
      </html>
  )
}
